# Generated by Django 2.0.2 on 2020-06-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolemenu',
            options={'ordering': ['-id'], 'verbose_name': '角色菜单中间表', 'verbose_name_plural': '角色菜单中间表'},
        ),
    ]
