# Generated by Django 2.2.5 on 2020-07-02 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_userprofile_user_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('4cffc198-9a84-4697-b602-19cf1d7eb64a'), verbose_name='用户JWT秘钥'),
        ),
    ]
