# Generated by Django 2.0.2 on 2020-06-24 07:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200624_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='roles',
            new_name='role_list',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='peoples',
            new_name='user_list',
        ),
        migrations.AlterField(
            model_name='menu',
            name='code',
            field=models.CharField(blank=True, help_text='编码', max_length=50, null=True, verbose_name='编码'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='create_user',
            field=models.IntegerField(blank=True, help_text='创建者', null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, help_text='图标', max_length=50, null=True, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_delete',
            field=models.BooleanField(default=False, help_text='是否删除', verbose_name='逻辑删除'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_top',
            field=models.BooleanField(default=False, help_text='是否是顶级菜单', verbose_name='首页显示'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(help_text='菜单名', max_length=32, unique=True, verbose_name='菜单名'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父菜单', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_menu', to='system.Menu', verbose_name='父菜单'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='update_user',
            field=models.IntegerField(blank=True, help_text='修改者', null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, help_text='url', max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='role',
            name='create_user',
            field=models.IntegerField(blank=True, help_text='创建者', null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_delete',
            field=models.BooleanField(default=False, help_text='是否删除', verbose_name='逻辑删除'),
        ),
        migrations.AlterField(
            model_name='role',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='role',
            name='update_user',
            field=models.IntegerField(blank=True, help_text='修改者', null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='create_user',
            field=models.IntegerField(blank=True, help_text='创建者', null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='is_delete',
            field=models.BooleanField(default=False, help_text='是否删除', verbose_name='逻辑删除'),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='update_user',
            field=models.IntegerField(blank=True, help_text='修改者', null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='create_user',
            field=models.IntegerField(blank=True, help_text='创建者', null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='is_delete',
            field=models.BooleanField(default=False, help_text='是否删除', verbose_name='逻辑删除'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='update_user',
            field=models.IntegerField(blank=True, help_text='修改者', null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_user',
            field=models.IntegerField(blank=True, help_text='创建者', null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_delete',
            field=models.BooleanField(default=False, help_text='是否删除', verbose_name='逻辑删除'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='update_user',
            field=models.IntegerField(blank=True, help_text='修改者', null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='create_user',
            field=models.IntegerField(blank=True, help_text='创建者', null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='is_delete',
            field=models.BooleanField(default=False, help_text='是否删除', verbose_name='逻辑删除'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='update_user',
            field=models.IntegerField(blank=True, help_text='修改者', null=True, verbose_name='修改人'),
        ),
    ]
