# Generated by Django 2.0.2 on 2020-06-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200626_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='text',
            field=models.TextField(default='', help_text='留言内容', max_length=1000, verbose_name='留言内容'),
        ),
    ]
