# Generated by Django 2.2.5 on 2020-07-02 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20200702_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_secret',
            field=models.CharField(default=uuid.UUID('5e0b63d5-8642-4868-9811-35860f15a4f6'), max_length=500, verbose_name='用户JWT秘钥'),
        ),
    ]
