# Generated by Django 2.0.2 on 2020-06-24 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20200624_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='role_list',
        ),
        migrations.AddField(
            model_name='menu',
            name='roles',
            field=models.ManyToManyField(related_name='menu_list', through='system.RoleMenu', to='system.Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='user_list',
            field=models.ManyToManyField(related_name='role_list', through='system.UserRole', to=settings.AUTH_USER_MODEL),
        ),
    ]
