# Generated by Django 2.0.2 on 2020-06-27 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_usermessage_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.IntegerField(blank=True, help_text='创建者', null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_user', models.IntegerField(blank=True, help_text='修改者', null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(help_text='标题', max_length=100, verbose_name='标题')),
                ('desc', models.CharField(help_text='描述', max_length=1000, verbose_name='描述')),
                ('type', models.IntegerField(choices=[(1, '一级类别'), (2, '二级类别'), (3, '三级类别')], default=1, help_text='类型', verbose_name='类型')),
                ('code', models.CharField(help_text='编码', max_length=100, verbose_name='编码')),
                ('is_top', models.BooleanField(default=False, help_text='是否是顶级菜单', verbose_name='是否是顶级菜单')),
                ('parent_id', models.IntegerField(blank=True, default=None, help_text='父菜单', null=True, verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
    ]
