# Generated by Django 2.0.2 on 2020-06-27 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(blank=True, default=None, help_text='父菜单', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='system.Category', verbose_name='父菜单'),
        ),
    ]
