# Generated by Django 2.2.5 on 2020-07-03 20:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20200703_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='button_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='button_role', to='system.Button'),
        ),
        migrations.AddField(
            model_name='role',
            name='page_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_role', to='system.Page'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_secret',
            field=models.CharField(default=uuid.UUID('f3bb33ab-0891-44aa-be23-111aee2b9bb2'), max_length=500, verbose_name='用户JWT秘钥'),
        ),
        migrations.DeleteModel(
            name='RolePageButton',
        ),
    ]
