# Generated by Django 2.0.2 on 2020-06-27 07:43

from django.db import migrations, models
import django.utils.timezone
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20200627_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.IntegerField(blank=True, help_text='创建者', null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_user', models.IntegerField(blank=True, help_text='修改者', null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, help_text='修改时间', verbose_name='修改时间')),
                ('good_sn', models.IntegerField(blank=True, help_text='货物号', null=True, verbose_name='货物号')),
                ('name', models.CharField(blank=True, help_text='商品名', max_length=100, null=True, verbose_name='商品名')),
                ('desc', models.TextField(blank=True, help_text='商品的描述', max_length=100, null=True, verbose_name='商品的描述')),
                ('image', models.ImageField(help_text='商品的主图片', upload_to='goods', verbose_name='商品的主图片')),
                ('market_price', models.DecimalField(decimal_places=8, default=0.0, help_text='市场的价格', max_digits=11, verbose_name='市场的价格')),
                ('shop_price', models.DecimalField(decimal_places=8, default=0.0, help_text='本店的价格', max_digits=11, verbose_name='本店的价格')),
                ('click_num', models.IntegerField(default=0, help_text='点击次数', verbose_name='点击次数')),
                ('favorate_num', models.IntegerField(default=0, help_text='喜欢次数', verbose_name='喜欢次数')),
                ('sold_num', models.IntegerField(default=0, help_text='已卖数量', verbose_name='已卖数量')),
                ('good_num', models.IntegerField(default=0, help_text='库存数量', verbose_name='库存数量')),
                ('is_hot', models.BooleanField(default=False, help_text='商品是否热卖', verbose_name='商品是否热卖')),
                ('is_new', models.BooleanField(default=False, help_text='是否新产品', verbose_name='是否新产品')),
                ('ship_free', models.BooleanField(default=False, help_text='是否包邮', verbose_name='是否包邮')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': '类别', 'verbose_name_plural': '类别'},
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(blank=True, default=None, help_text='分类', null=True, on_delete=system.models.Category, to='system.Category', verbose_name='分类'),
        ),
    ]
