# Generated by Django 2.0.2 on 2020-06-27 07:44

from django.db import migrations, models
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20200627_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ForeignKey(blank=True, default=None, help_text='分类', null=True, on_delete=system.models.Category, related_name='good_list', to='system.Category', verbose_name='分类'),
        ),
    ]
