# Generated by Django 2.2.5 on 2020-07-03 20:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20200703_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='button_list',
            field=models.ManyToManyField(related_name='button_role', to='system.Button'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_secret',
            field=models.CharField(default=uuid.UUID('b6c7ef4f-ee5f-48cb-8b4c-99036523a3dc'), max_length=500, verbose_name='用户JWT秘钥'),
        ),
    ]
