# Generated by Django 2.0.2 on 2020-06-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20200627_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, help_text='商品的主图片', null=True, upload_to='goods', verbose_name='商品的主图片'),
        ),
    ]
