# Generated by Django 2.2.5 on 2020-07-03 20:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20200703_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='page_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_role', to='system.Page'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_secret',
            field=models.CharField(default=uuid.UUID('b1ce7104-d9c6-49e6-89b4-f9ec5763b224'), max_length=500, verbose_name='用户JWT秘钥'),
        ),
    ]
