# Generated by Django 2.0.2 on 2020-06-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20200627_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='market_price',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='市场的价格', max_digits=20, verbose_name='市场的价格'),
        ),
    ]
