# Generated by Django 2.2.5 on 2020-07-03 20:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20200703_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_secret',
            field=models.CharField(default=uuid.UUID('c3ff7ef3-bc25-4307-a35e-ee40d48b58b0'), max_length=500, verbose_name='用户JWT秘钥'),
        ),
    ]
