# Generated by Django 2.0.2 on 2020-06-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20200627_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='desc',
            field=models.TextField(blank=True, help_text='商品的描述', max_length=1000, null=True, verbose_name='商品的描述'),
        ),
    ]
