# Generated by Django 2.2.5 on 2020-07-03 20:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_auto_20200703_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_secret',
            field=models.CharField(default=uuid.UUID('d6f0666d-f140-4fa8-a229-118ca4526b8a'), max_length=500, verbose_name='用户JWT秘钥'),
        ),
    ]
