# Generated by Django 2.0.2 on 2020-06-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_userfavorate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavorate',
            unique_together={('user', 'good')},
        ),
    ]
