# Generated by Django 2.2.5 on 2020-07-03 21:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_auto_20200703_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='albumimage',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='albumimage',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='button',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='button',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='good',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='ordergood',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ordergood',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='track',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='userfavorate',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userfavorate',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_secret',
            field=models.CharField(default=uuid.UUID('2edf8aba-3611-49be-96e6-9b682016be49'), max_length=500, verbose_name='用户JWT秘钥'),
        ),
    ]
