# Generated by Django 2.0.2 on 2020-06-27 09:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_auto_20200627_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.IntegerField(blank=True, help_text='创建者', null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_user', models.IntegerField(blank=True, help_text='修改者', null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, help_text='修改时间', verbose_name='修改时间')),
                ('image', models.ImageField(blank=True, help_text='图片', null=True, upload_to='banner', verbose_name='图片')),
                ('index', models.IntegerField(default=1, help_text='轮播顺序', verbose_name='轮播顺序')),
                ('good', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='system.Good', verbose_name='商品')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'ordering': ['-id'],
            },
        ),
    ]
