# Generated by Django 2.2.5 on 2020-07-03 21:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_auto_20200703_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='albumimage',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='ordergood',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='structure',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='userfavorate',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='usermessage',
            old_name='status',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='button',
            name='status',
        ),
        migrations.AddField(
            model_name='button',
            name='state',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_secret',
            field=models.CharField(default=uuid.UUID('5dae090d-eea2-4039-8c77-caffbcf3539c'), max_length=500, verbose_name='用户JWT秘钥'),
        ),
    ]
