# Generated by Django 2.2.5 on 2020-07-03 21:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_auto_20200703_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_secret',
            field=models.CharField(default=uuid.UUID('c89151d5-e431-4dc0-8113-21f21a3b18ae'), max_length=500, verbose_name='用户JWT秘钥'),
        ),
    ]
