# Generated by Django 2.0.2 on 2020-06-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='good',
            field=models.ForeignKey(blank=True, help_text='商品', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Good', verbose_name='商品'),
        ),
    ]
