# Generated by Django 2.2.5 on 2020-07-03 21:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_auto_20200703_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ordergood',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userfavorate',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_secret',
            field=models.CharField(default=uuid.UUID('0749e0d7-680e-4822-a632-18d285123f13'), max_length=500, verbose_name='用户JWT秘钥'),
        ),
    ]
