# Generated by Django 2.0.2 on 2020-06-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_shopcart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopCart',
            new_name='Cart',
        ),
    ]
