# Generated by Django 2.2.5 on 2020-07-04 00:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_auto_20200703_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_secret',
            field=models.CharField(default=uuid.UUID('f51c894d-a532-4ddc-b3e9-2847d4b2e7ae'), max_length=500, verbose_name='用户JWT秘钥'),
        ),
    ]
