# Generated by Django 2.0.2 on 2020-06-27 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_auto_20200627_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.IntegerField(blank=True, help_text='创建者', null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_user', models.IntegerField(blank=True, help_text='修改者', null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, help_text='修改时间', verbose_name='修改时间')),
                ('order_sn', models.CharField(blank=True, help_text='订单号', max_length=100, null=True, unique=True, verbose_name='订单号')),
                ('pay_type', models.IntegerField(choices=[(1, '微信'), (2, '支付宝')], default=1, help_text='支付方式', verbose_name='支付方式')),
                ('order_status', models.CharField(choices=[('TRADE_SUCCESS', '成功'), ('TRADE_CLOSED', '超时关闭'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_FINISHED', '交易结束'), ('paying', '待支付')], default='paying', help_text='支付状态', max_length=100, verbose_name='支付状态')),
                ('nonce_str', models.CharField(blank=True, help_text='微信订单号', max_length=100, null=True, verbose_name='微信订单号')),
                ('trade_no', models.CharField(blank=True, help_text='支付宝订单号', max_length=100, null=True, verbose_name='支付宝订单号')),
                ('order_num', models.DecimalField(decimal_places=3, default=0.0, help_text='订单金额', max_digits=20, verbose_name='订单金额')),
                ('pay_time', models.DateTimeField(blank=True, help_text='支付时间', null=True, verbose_name='支付时间')),
                ('post_script', models.TextField(blank=True, help_text='用户备注', max_length=200, null=True, verbose_name='用户备注')),
                ('address', models.CharField(help_text='送货地址', max_length=100, verbose_name='送货地址')),
                ('sign_name', models.CharField(help_text='收货人', max_length=30, verbose_name='收货人')),
                ('sign_mobile', models.CharField(help_text='收货人电话', max_length=20, verbose_name='收货人电话')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.IntegerField(blank=True, help_text='创建者', null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_user', models.IntegerField(blank=True, help_text='修改者', null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, help_text='修改时间', verbose_name='修改时间')),
                ('num', models.IntegerField(default=0, verbose_name='商品数量')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Good')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_list', to='system.Order')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
                'ordering': ['-id'],
            },
        ),
    ]
