# Generated by Django 2.2.5 on 2020-07-04 00:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_auto_20200704_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_secret',
            field=models.CharField(default=uuid.UUID('d1a7cbcf-599c-45e8-930b-c361657400c0'), max_length=500, verbose_name='用户JWT秘钥'),
        ),
    ]
