# Generated by Django 2.2.5 on 2020-07-04 02:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_auto_20200704_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='role_list',
            new_name='roles',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_secret',
            field=models.CharField(default=uuid.UUID('6c600c70-47c6-445d-bf8f-e787ad4467dd'), max_length=500, verbose_name='用户JWT秘钥'),
        ),
    ]
