# Generated by Django 2.0.2 on 2020-06-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_order_ordergood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='category',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='good',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='ordergood',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='role',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='track',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='userfavorate',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
    ]
