# Generated by Django 2.2.5 on 2020-07-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_remove_userprofile_user_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='avatar'),
        ),
    ]
