# Generated by Django 2.2.5 on 2020-07-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/avatar/default.jpg', upload_to='avatar'),
        ),
    ]
