# Generated by Django 2.2.5 on 2020-07-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_auto_20200704_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
