# Generated by Django 2.2.5 on 2020-07-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_remove_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
