# Generated by Django 2.2.5 on 2020-07-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0027_auto_20200704_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
