# Generated by Django 2.2.5 on 2020-08-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0031_patent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='abstract',
            field=models.CharField(blank=True, help_text='摘要', max_length=1024, null=True, verbose_name='摘要'),
        ),
    ]
