# Generated by Django 2.2.5 on 2020-08-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0032_auto_20200805_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.AddField(
            model_name='page',
            name='code',
            field=models.CharField(default='list', max_length=100),
        ),
    ]
