# Generated by Django 2.2.5 on 2020-08-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0033_auto_20200806_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
