# Generated by Django 2.2.5 on 2020-08-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0035_auto_20200806_2055'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='button',
        #     old_name='code',
        #     new_name='url',
        # ),
        # migrations.AlterField(
        #     model_name='page',
        #     name='url',
        #     field=models.CharField(max_length=100, unique=True),
        # ),
    ]
