# Generated by Django 2.2.5 on 2020-08-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0036_auto_20200806_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
