# Generated by Django 2.2.5 on 2020-08-06 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0037_auto_20200806_2143'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='button',
        #     old_name='code',
        #     new_name='url',
        # ),
    ]
