# Generated by Django 2.2.5 on 2020-08-06 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0038_auto_20200806_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='url',
            new_name='code',
        ),
    ]
