# Generated by Django 2.2.5 on 2020-08-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0039_auto_20200806_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='电话'),
        ),
    ]
