# Generated by Django 2.0.2 on 2020-07-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_nav',
            field=models.BooleanField(default=True),
        ),
    ]
