# Generated by Django 2.0.2 on 2020-07-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_category_is_nav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
