# Generated by Django 2.0.2 on 2020-07-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200710_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderbar',
            name='content',
            field=models.CharField(blank=True, help_text='不是html可以为空', max_length=500, null=True),
        ),
    ]
