# Generated by Django 2.0.2 on 2020-06-29 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200629_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='youneed_konw',
            new_name='youneed_know',
        ),
    ]
