# Generated by Django 2.0.2 on 2020-06-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_video_learn_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='learn_times',
        ),
        migrations.AddField(
            model_name='lesson',
            name='learn_times',
            field=models.IntegerField(default=0),
        ),
    ]
