# Generated by Django 2.2.5 on 2020-06-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200629_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
