# Generated by Django 2.2.5 on 2020-07-06 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_buttontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='actionsOption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_actionsOption', to='system.Permission'),
        ),
        migrations.AddField(
            model_name='permission',
            name='check_all',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_permission', to='system.Permission'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='type',
            field=models.IntegerField(choices=[(2, '页面'), (1, '菜单'), (3, '按钮')], default=1),
        ),
    ]
