# Generated by Django 2.2.5 on 2020-07-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20200706_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buttontype',
            options={'verbose_name': '按钮'},
        ),
    ]
