# Generated by Django 2.2.5 on 2020-07-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20200706_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='create_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='update_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='type',
            field=models.IntegerField(choices=[(2, '页面'), (1, '菜单'), (3, '按钮')], default=1),
        ),
    ]
