# Generated by Django 2.0.2 on 2020-07-10 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('type', models.IntegerField(choices=[(0, '删除'), (1, '正常')], default=1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_content', to='article.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
