# Generated by Django 2.2.12 on 2020-06-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='role',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='状态'),
        ),
    ]
